"""
Unit tests for the LLM provider layer, LLMRouter, and fallback mechanics.
"""

from unittest.mock import AsyncMock, patch
import pytest
from fastapi.testclient import TestClient

from app.services.llm.base import (
    LLMAuthenticationError,
    LLMRateLimitError,
    LLMTimeoutError,
)
from app.services.llm.cloud_provider import CloudProvider
from app.services.llm.ollama_provider import OllamaProvider
from app.services.llm.router import LLMRouter
from app.services.llm.types import LLMResponse


@pytest.fixture
def mock_ollama_provider():
    provider = AsyncMock(spec=OllamaProvider)
    provider.provider_name = "ollama"
    provider.model_name = "llama3.2:3b"
    provider.is_available.return_value = True
    provider.complete.return_value = LLMResponse(
        content="This is an answer generated locally by Ollama.",
        model="llama3.2:3b",
        provider="ollama",
        served_by="ollama",
        latency_ms=150.0,
        usage={"prompt_tokens": 20, "completion_tokens": 15, "total_tokens": 35},
    )
    return provider


@pytest.fixture
def mock_cloud_provider():
    provider = AsyncMock(spec=CloudProvider)
    provider.provider_name = "groq"
    provider.model_name = "llama-3.3-70b-versatile"
    provider.is_available.return_value = True
    provider.complete.return_value = LLMResponse(
        content="This is an answer generated by Groq Cloud LLM.",
        model="llama-3.3-70b-versatile",
        provider="groq",
        served_by="groq",
        latency_ms=80.0,
        usage={"prompt_tokens": 20, "completion_tokens": 15, "total_tokens": 35},
    )
    return provider


@pytest.mark.asyncio
async def test_ollama_provider_direct_mock():
    """Test OllamaProvider direct completion parsing."""
    from unittest.mock import MagicMock
    provider = OllamaProvider(base_url="http://localhost:11434", model="llama3.2:3b")

    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.json.return_value = {
        "message": {"content": "Ollama local response."},
        "prompt_eval_count": 10,
        "eval_count": 12,
    }

    with patch("httpx.AsyncClient.post", new_callable=AsyncMock, return_value=mock_resp):
        resp = await provider.complete(prompt="What is product strategy?")
        assert resp.content == "Ollama local response."
        assert resp.model == "llama3.2:3b"
        assert resp.provider == "ollama"
        assert resp.served_by == "ollama"
        assert resp.usage["total_tokens"] == 22


@pytest.mark.asyncio
async def test_cloud_provider_direct_mock():
    """Test CloudProvider direct completion parsing."""
    from unittest.mock import MagicMock
    provider = CloudProvider(
        provider="groq",
        api_key="gsk_valid_test_key",
        model="llama-3.3-70b-versatile",
    )

    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.json.return_value = {
        "choices": [{"message": {"content": "Cloud Groq response."}}],
        "usage": {"prompt_tokens": 15, "completion_tokens": 10, "total_tokens": 25},
    }

    with patch("httpx.AsyncClient.post", new_callable=AsyncMock, return_value=mock_resp):
        resp = await provider.complete(prompt="What is PMF?")
        assert resp.content == "Cloud Groq response."
        assert resp.provider == "groq"
        assert resp.served_by == "groq"
        assert resp.model == "llama-3.3-70b-versatile"


@pytest.mark.asyncio
async def test_router_ollama_primary(mock_ollama_provider, mock_cloud_provider):
    """Test that LLMRouter with primary='ollama' routes directly to Ollama."""
    router = LLMRouter(
        primary_provider="ollama",
        ollama_provider=mock_ollama_provider,
        cloud_provider=mock_cloud_provider,
    )

    resp = await router.complete(prompt="Explain growth loops.")
    assert resp.content == "This is an answer generated locally by Ollama."
    assert resp.served_by == "ollama"
    mock_ollama_provider.complete.assert_called_once()
    mock_cloud_provider.complete.assert_not_called()


@pytest.mark.asyncio
async def test_router_cloud_primary_success(mock_ollama_provider, mock_cloud_provider):
    """Test that LLMRouter with primary='cloud' uses cloud when healthy."""
    router = LLMRouter(
        primary_provider="cloud",
        ollama_provider=mock_ollama_provider,
        cloud_provider=mock_cloud_provider,
    )

    resp = await router.complete(prompt="Explain growth loops.")
    assert resp.content == "This is an answer generated by Groq Cloud LLM."
    assert resp.served_by == "groq"
    mock_cloud_provider.complete.assert_called_once()
    mock_ollama_provider.complete.assert_not_called()


@pytest.mark.asyncio
async def test_router_fallback_on_rate_limit(mock_ollama_provider, mock_cloud_provider):
    """Test that cloud 429 rate limit triggers seamless Ollama fallback."""
    mock_cloud_provider.complete.side_effect = LLMRateLimitError("Rate limit exceeded (HTTP 429)")

    router = LLMRouter(
        primary_provider="cloud",
        ollama_provider=mock_ollama_provider,
        cloud_provider=mock_cloud_provider,
    )

    resp = await router.complete(prompt="Explain retention cohorts.")
    assert resp.content == "This is an answer generated locally by Ollama."
    assert resp.served_by == "ollama-fallback"
    mock_cloud_provider.complete.assert_called_once()
    mock_ollama_provider.complete.assert_called_once()


@pytest.mark.asyncio
async def test_router_fallback_on_timeout(mock_ollama_provider, mock_cloud_provider):
    """Test that cloud request timeout triggers seamless Ollama fallback."""
    mock_cloud_provider.complete.side_effect = LLMTimeoutError("Request timed out after 30s")

    router = LLMRouter(
        primary_provider="cloud",
        ollama_provider=mock_ollama_provider,
        cloud_provider=mock_cloud_provider,
    )

    resp = await router.complete(prompt="Explain retention cohorts.")
    assert resp.content == "This is an answer generated locally by Ollama."
    assert resp.served_by == "ollama-fallback"
    mock_ollama_provider.complete.assert_called_once()


@pytest.mark.asyncio
async def test_router_fallback_on_missing_api_key(mock_ollama_provider, mock_cloud_provider):
    """Test that missing cloud API key triggers seamless Ollama fallback without throwing."""
    mock_cloud_provider.is_available.return_value = False

    router = LLMRouter(
        primary_provider="cloud",
        ollama_provider=mock_ollama_provider,
        cloud_provider=mock_cloud_provider,
    )

    resp = await router.complete(prompt="Explain virality.")
    assert resp.content == "This is an answer generated locally by Ollama."
    assert resp.served_by == "ollama-fallback"
    # Cloud complete() is bypassed because is_available is False
    mock_cloud_provider.complete.assert_not_called()
    mock_ollama_provider.complete.assert_called_once()


@pytest.mark.asyncio
async def test_router_fallback_on_auth_error(mock_ollama_provider, mock_cloud_provider):
    """Test that invalid cloud API key (401 error) triggers seamless Ollama fallback."""
    mock_cloud_provider.complete.side_effect = LLMAuthenticationError("Invalid API key")

    router = LLMRouter(
        primary_provider="cloud",
        ollama_provider=mock_ollama_provider,
        cloud_provider=mock_cloud_provider,
    )

    resp = await router.complete(prompt="Explain activation metrics.")
    assert resp.content == "This is an answer generated locally by Ollama."
    assert resp.served_by == "ollama-fallback"
    mock_cloud_provider.complete.assert_called_once()
    mock_ollama_provider.complete.assert_called_once()


def test_get_config_endpoint(client: TestClient):
    """Test GET /api/config endpoint response structure."""
    resp = client.get("/api/config")
    assert resp.status_code == 200
    data = resp.json()
    assert "current_provider" in data
    assert "current_model" in data
    assert data["fallback_provider"] == "ollama"
    assert "fallback_model" in data
    assert isinstance(data["available_providers"], list)
    assert "ollama" in data["available_providers"]
    assert "cloud_configured" in data
